name: CI

on: [push]

jobs:
  build:

    name: surge.sh deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm i -g surge
    - run: npm ci --production
    - run: echo ${{ secrets.ENV_VARS }} > .env.production
    - run: npm run build
    - run: surge ./public/ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
